/**
 * ...
 * @author 
 */

package com.acrossoft.colosseus;

enum EditMode 
{
	NONE;
	SELECTED;
	CREATE_PLACE_CENTER;
	CREATE_ADD_POINT;
	MOVE_CHOOSE;
	MOVE_WAIT_FOR_DROP;
	ROTATE_CHOOSE;
	ROTATE_WAIT_FOR_DROP;
	DELETE_CHOOSE;
	PLACE_TURRET_CHOOSE;
	PLACE_TURRET_WAIT_FOR_DROP;
	DELETE_TURRET;
	CHANGE_TURRET;
}